#!/usr/bin/env bash

set -eou pipefail

(
	cd $(git rev-parse --show-toplevel)
  docker run --rm \
    -v $(pwd):/opt/workdir \
    -u $(id -u):$(id -g) \
    polygonio/swagger-cli \
    bundle "_specs_/rest/index.yml" --dereference --outfile "_built_/rest.json" --type json
)
