#!/usr/bin/env bash

set -eou pipefail

(
  cd $(git rev-parse --show-toplevel)
  docker run \
    -v $(pwd):/opt/workdir \
    -u $(id -u):$(id -g) \
    polygonio/swagger-cli \
    bundle _spec_/index.yml --outfile _built_/spec.yml --type yaml
)
