#!/usr/bin/env bash

set -eou pipefail

(
	cd $(git rev-parse --show-toplevel)
  docker run \
    -v $(pwd):/opt/workdir \
    polygonio/swagger-cli \
    bundle "_spec_/index.yml" --dereference --outfile "_built_/spec.json" --type json
)
