#!/usr/bin/env bash

set -eou pipefail

(
  cd $(git rev-parse --show-toplevel)
  docker run \
    -p 8080:8080 \
    -e SWAGGER_JSON=/spec/spec.yml \
    -v $(pwd)/_built_:/spec \
    -v $(pwd)/spec:/usr/share/nginx/html/spec \
    swaggerapi/swagger-ui
)
