#!/usr/bin/env bash

set -eou pipefail

main() {
	(
		cd $(git rev-parse --show-toplevel)
		docker run --rm \
			-p 8080:8080 \
			-e SWAGGER_JSON="/spec/spec.json" \
			-v $(pwd)/_built_:/spec \
			swaggerapi/swagger-ui
	)
}

main
