---
kind: pipeline
type: docker
name: review

platform:
  os: linux
  arch: amd64

steps:
- name: validate spec
  image: polygonio/swagger-cli
  commands:
  - swagger-cli validate _specs_/rest/index.yml
  - swagger-cli validate _specs_/websocket/index.yml

trigger:
  branch:
  - master
  event:
  - pull_request

---
kind: pipeline
type: docker
name: build and deploy to staging

platform:
  os: linux
  arch: amd64

steps:
- name: bundle spec
  image: polygonio/swagger-cli
  commands:
  - swagger-cli bundle _specs_/rest/index.yml --dereference --outfile _built_/rest.json --type json
  - swagger-cli bundle _specs_/websocket/index.yml --dereference --outfile _built_/websocket.json --type json

- name: upload rest spec
  image: plugins/gcs
  settings:
    cache_control: no-cache
    source: _built_/rest.json
    target: polygon-io-public/docs/api_specs/platform/staging/rest.json
    token:
      from_secret: gcs_api_spec_editor_token

- name: upload websocket spec
  image: plugins/gcs
  settings:
    cache_control: no-cache
    source: _built_/websocket.json
    target: polygon-io-public/docs/api_specs/platform/staging/websocket.json
    token:
      from_secret: gcs_api_spec_editor_token

- name: upload prod rest spec
  image: plugins/gcs
  settings:
    cache_control: no-cache
    source: _built_/rest.json
    target: polygon-io-public/docs/api_specs/platform/prod/rest.json
    token:
      from_secret: gcs_api_spec_editor_token

- name: upload prod websocket spec
  image: plugins/gcs
  settings:
    cache_control: no-cache
    source: _built_/websocket.json
    target: polygon-io-public/docs/api_specs/platform/prod/websocket.json
    token:
      from_secret: gcs_api_spec_editor_token

trigger:
  branch:
  - master
  event:
  - push

...
