---
  kind: pipeline
  type: docker
  name: review
  
  platform:
    os: linux
    arch: amd64
  
  steps:
  - name: validate spec
    image: polygonio/swagger-cli
    commands:
    - swagger-cli validate _spec_/*.yaml --outfile _built_/swagger.json --type json

  trigger:
    branch:
    - master
    event:
    - pull_request
  
---
  kind: pipeline
  type: docker
  name: build and deploy to staging

  platform:
    os: linux
    arch: amd64

  steps:
  - name: bundle spec
    image: polygonio/swagger-cli
    commands:
    - swagger-cli bundle _spec_/*.yaml --outfile _built_/swagger.json --type json

  - name: upload spec
    image: plugins/gcs
    settings:
      cache_control: no-cache
      source: _built_/swagger.json
      target: polygon-io-public/docs/api_specs/platform/staging/swagger.json
      token:
        from_secret: gcs_api_spec_editor_token

  trigger:
    branch:
    - master
    event:
    - push

---
  kind: pipeline
  type: docker
  name: build and deploy to production

  platform:
    os: linux
    arch: amd64

  steps:
  - name: bundle spec
    image: polygonio/swagger-cli
    commands:
    - swagger-cli bundle _spec_/*.yaml --outfile _built_/swagger.json --type json

  - name: upload spec
    image: plugins/gcs
    settings:
      cache_control: no-cache
      source: _built_/swagger.json
      target: polygon-io-public/docs/api_specs/platform/swagger.json
      token:
        from_secret: gcs_api_spec_editor_token

  trigger:
    event:
    - tag
    ref:
    - refs/tags/production-*
  