StocksTickerParam:
  name: ticker
  in: query
  description: |
    Specify a ticker symbol or use * to retrieve all tickers.
    You can also use a comma separated list to retrieve multiple tickers.
  required: true
  schema:
    type: string
    pattern: /^([a-zA-Z]+|\*)$/
  example: '*'
ForexTickerParam:
  name: ticker
  in: query
  description: |
    Specify a forex pair in the format {from}/{to} or use *
    to retrieve all forex pairs.  You can also use a comma 
    separated list to retrieve multiple tickers.
  required: true
  schema:
    type: string
  example: '*'
CryptoTickerParam:
  name: ticker
  in: query
  description: |
    Specify a crypto pair in the format {from}-{to} or use *
    to retrieve all crypto pairs.  You can also use a comma 
    separated list to retrieve multiple tickers.
  required: true
  schema:
    type: string
  example: '*'